### ISSUE TITLE
Future Developement

### ISSUE THREAD

**Issue by maxnuglisch** [actumn/aepx.js#1]
hey ;)
I recently discovered your project and it helped me a LOT.
Are you still developing on it? If not could you help me pushing it further by explaining me how you got the information about the hex values and how to convert them back to readable data?

Greets
Max ^^

**Comment by actumn** [comment]
Hi!  
Thanks for being interested on this project!  
I'm glad that it helped you a lot :).
  
About developing, well, I will work on someday, but I'm lazy so I don't know when it'll be :).
  
Since I have no knowledge about reverse engineering, 
I find out the information about the hex value by
1. just read the hex values in after effects project file (aepx) and assume what it would be.  
2. open aepx via after effects, change some value (fps, start frame, etc.), save and check the modified part of aepx
  
The below research is so useful for it.
- https://github.com/inlife/aftereffects-project-research

I think the below image helps you understanding after effects project file structure
![IMAGE](http://docs.aenhancers.com/_images/objectmodel.png)

And online tools for reading hex values
- [for decimal number](https://www.binaryhexconverter.com/decimal-to-hex-converter)
- [for floating point](https://gregstoll.com/~gregstoll/floattohex/)
- [for ascii string](https://codebeautify.org/hex-string-converter)

I hope this information helps you.
