### ISSUE TITLE
Parse Properties

### ISSUE THREAD

**Issue by jimstagram** [actumn/aepx.js#4]
Hi,

This project is great - nice work!

For me, it nicely builds the structures for folders, compositions, and then layers on those compositions. I was wondering if it could also then retrieve effects and text document properties for each layer.

I've noticed the lines for parsing the properties are commented out:

  /*
  if (layer.tdgp) {
    result.tdgp = parseProperty(layer.tdgp[0]);
  }
  */

Uncommenting doesn't seem to achieve anything - so I was wondering if you had any pointers how I could progress this feature? I'm not quite able to make sense of the 'tdgp' structure.

Thanks.

**Comment by actumn** [comment]
Hi.
I'm happy that you're working with `aepx.js`.

Tdgp part is a little confusing because there's bunch of special cases like `ADBE Transform Group ` or `dropShadow/enabled ` so it requires special rules.

For example, take a look `examples/input/1layer.aepx` https://github.com/actumn/aepx.js/blob/f35e24bc88baf68b4b8e45c9e1a8122cac8ae5bd/examples/input/1layer.aepx#L45-L84

As you can see, `tdmn` describes property name of tdgp below. `bdata` is binary data describing name written in ascii code.
The most important part is `btdk` which is describing all about text such as text font, size, text contents and so on as I assume `adobe text engine data`

Another example, take a look
https://github.com/actumn/aepx.js/blob/f35e24bc88baf68b4b8e45c9e1a8122cac8ae5bd/examples/input/1layer.aepx#L403-L417
Above describes `ADBE Transform Group` which describes I guess "Transform effect" of the layer.
Below, there are `tdb4` and `cdat` which is consisted of floating point values (not completely, just presume).
- 408e000000000000 -> 960.0
- 3f1a36e2eb1c432d -> 0.0001
- 3ff0000000000000 -> 1.0

But it requires additional research to know what it means.


It would be helpful to use online tools 
- https://gregstoll.com/~gregstoll/floattohex/
- https://codebeautify.org/hex-string-converter

The project is built on MIT license so feel free to fork it and customize as you want If you don't mind.

Thanks.

**Comment by jimstagram** [comment]
Amazing, thank you!
